### ISSUE TITLE
shikigva=40

### ISSUE THREAD

**Issue by isNextJuly** [bosphere/hackintosh-deskmini-310-i7-8700#1]
shikigva=40,是为了解决什么问题？我的EFI 目前 drm 保护的内容都没得问题。唯有就是 fcpx 转场之类的会 引起 关机不断电。你的有这个问题吗

**Comment by bosphere** [comment]
我没有用 fcpx，所以无法给出准确答案。添加这个配置并没有什么特殊的缘由，只是因为参考了 Hackintosh Vanilla 的教程，具体你可以参考这里：https://hackintosh.gitbook.io/-r-hackintosh-vanilla-desktop-guide/config.plist-per-hardware/coffee-lake#arguments
